<?php
/**
 * Copyright © Bluebirdday. All rights reserved.
 *
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Bluebirdday\SpeedcurveMagento\Helper\Data $helper
 * @var \Magento\Framework\Escaper $escaper
 */
$helper = $this->helper(\Bluebirdday\SpeedcurveMagento\Helper\Data::class);
$categoryPageLabel = $helper->getCategoryPageLabel();
?>
<script type="text/x-magento-init">
    {
        "*": {
            "bluebirddaySpeedcurvePageLabel": {
                "pageLabel": "<?= $escaper->escapeJs($categoryPageLabel) ?>"
            }
        }
    }
</script> 